[package]
name = "manager"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
bevy_renet = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
uuid = { workspace = true }

common = { path = "../common" }
